apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestapp
  labels:
    app: nestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestapp
  template:
    metadata:
      labels:
        app: nestapp
    spec:
      containers:
        - name: nestapp
          image: kaashntr/devops-test:latest
          env:
              - name: REDIS_PASSWORD
                value: "${REDIS_PASSWORD}"
              - name: REDIS_HOST
                value: "${REDIS_HOST}"