apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nestapp-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nestapp
                port:
                  number: 3000
